import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
        <div className="absolute inset-0 bg-gradient-to-r from-purple-200 to-cyan-200 background-gradient-overlay h-screen w-screen z-[-100]"></div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
